// Date: 6/10/2015 7:51:24 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package ultimat3.expotech.items.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

/**
 * Model for rendering the Plasma Katana. 
 * 
 * @author Joetheantipro
 */
public class ModelPlasmaKatana extends ModelBase {
	// fields
	ModelRenderer	blade;
	ModelRenderer	handle1;
	ModelRenderer	handle2;
	ModelRenderer	handle3;
	ModelRenderer	handle4;
	
	public ModelPlasmaKatana() {
		textureWidth = 128;
		textureHeight = 128;
		
		blade = new ModelRenderer(this, 80, 0);
		blade.addBox(0F, -14.5F, -15F, 0, 12, 12);
		blade.setRotationPoint(0F, 0F, 0F);
		blade.setTextureSize(128, 128);
		blade.mirror = true;
		setRotation(blade, 0.7853982F, 0F, 0F);
		handle1 = new ModelRenderer(this, 92, 0);
		handle1.addBox(-0.5F, -0.5F, -7F, 1, 1, 3);
		handle1.setRotationPoint(0F, 0F, 0F);
		handle1.setTextureSize(128, 128);
		handle1.mirror = true;
		setRotation(handle1, 0F, 0F, 0F);
		handle2 = new ModelRenderer(this, 80, 0);
		handle2.addBox(-1.5F, -1.5F, -4F, 3, 3, 1);
		handle2.setRotationPoint(0F, 0F, 0F);
		handle2.setTextureSize(128, 128);
		handle2.mirror = true;
		setRotation(handle2, 0F, 0F, 0F);
		handle3 = new ModelRenderer(this, 80, 0);
		handle3.addBox(-1F, -1F, -3F, 2, 2, 8);
		handle3.setRotationPoint(0F, 0F, 0F);
		handle3.setTextureSize(128, 128);
		handle3.mirror = true;
		setRotation(handle3, 0F, 0F, 0F);
		handle4 = new ModelRenderer(this, 80, 0);
		handle4.addBox(-1.5F, -1.5F, 3F, 3, 3, 1);
		handle4.setRotationPoint(0F, 0F, 0F);
		handle4.setTextureSize(128, 128);
		handle4.mirror = true;
		setRotation(handle4, 0F, 0F, 0F);
	}
	
	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		blade.render(f5);
		handle1.render(f5);
		handle2.render(f5);
		handle3.render(f5);
		handle4.render(f5);
	}
	
	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
	
	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}
	
}
