// Date: 6/11/2015 6:52:45 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
 
 
 
 
 
 
package ultimat3.expotech.items.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
 
public class ModelParticlePistol extends ModelBase
{
  //fields
    ModelRenderer barrel1;
    ModelRenderer barrel2;
    ModelRenderer handle1;
    ModelRenderer handle2;
    ModelRenderer Shape1;
    ModelRenderer Shape2L;
    ModelRenderer Shape2R;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
   
  public ModelParticlePistol()
  {
    textureWidth = 32;
    textureHeight = 32;
     
      barrel1 = new ModelRenderer(this, 0, 0);
      barrel1.addBox(-1F, -2.5F, -8F, 2, 2, 4);
      barrel1.setRotationPoint(0.7F, 0.3F, -0.1F);
      barrel1.setTextureSize(32, 32);
      barrel1.mirror = true;
      setRotation(barrel1, 0F, 0.6981317F, 1.570796F);
      barrel2 = new ModelRenderer(this, 0, 6);
      barrel2.addBox(-0.5F, -0.5F, -7F, 1, 1, 3);
      barrel2.setRotationPoint(0.7F, 0.3F, -0.1F);
      barrel2.setTextureSize(32, 32);
      barrel2.mirror = true;
      setRotation(barrel2, 0F, 0.6981317F, 1.570796F);
      handle1 = new ModelRenderer(this, 12, 0);
      handle1.addBox(-0.5F, -1F, -1F, 1, 4, 2);
      handle1.setRotationPoint(0.7F, 0.3F, -0.1F);
      handle1.setTextureSize(32, 32);
      handle1.mirror = true;
      setRotation(handle1, 0.2617994F, 0.6981317F, 1.570796F);
      handle2 = new ModelRenderer(this, 9, 6);
      handle2.addBox(-1F, 2.5F, -0.5F, 2, 1, 2);
      handle2.setRotationPoint(0.7F, 0.3F, -0.1F);
      handle2.setTextureSize(32, 32);
      handle2.mirror = true;
      setRotation(handle2, 0F, 0.6981317F, 1.570796F);
      Shape1 = new ModelRenderer(this, 0, 10);
      Shape1.addBox(-1.5F, -4F, -4F, 3, 4, 3);
      Shape1.setRotationPoint(0.7F, 0.3F, -0.1F);
      Shape1.setTextureSize(32, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0.2617994F, 0.6981317F, 1.570796F);
//      Shape2L.mirror = true;
      Shape2L = new ModelRenderer(this, 0, 17);
      Shape2L.addBox(0.4F, -3F, -2F, 1, 1, 3);
      Shape2L.setRotationPoint(0.7F, 0.3F, -0.1F);
      Shape2L.setTextureSize(32, 32);
      Shape2L.mirror = true;
      setRotation(Shape2L, 0F, 0.6981317F, 1.570796F);
      Shape2L.mirror = false;
      Shape2R = new ModelRenderer(this, 0, 17);
      Shape2R.addBox(-1.4F, -3F, -2F, 1, 1, 3);
      Shape2R.setRotationPoint(0.7F, 0.3F, -0.1F);
      Shape2R.setTextureSize(32, 32);
      Shape2R.mirror = true;
      setRotation(Shape2R, 0F, 0.6981317F, 1.570796F);
      Shape3 = new ModelRenderer(this, 1, 21);
      Shape3.addBox(-1F, -2.5F, -2F, 2, 2, 4);
      Shape3.setRotationPoint(0.7F, 0.3F, -0.1F);
      Shape3.setTextureSize(32, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0.6981317F, 1.570796F);
      Shape4 = new ModelRenderer(this, 0, 22);
      Shape4.addBox(-0.5F, -2F, 1.5F, 1, 1, 1);
      Shape4.setRotationPoint(0.7F, 0.3F, -0.1F);
      Shape4.setTextureSize(32, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0.6981317F, 1.570796F);
  }
   
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    barrel1.render(f5);
    barrel2.render(f5);
    handle1.render(f5);
    handle2.render(f5);
    Shape1.render(f5);
    Shape2L.render(f5);
    Shape2R.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
  }
   
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
   
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }
 
}